import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers";
import ReactQueryProvider from "@/components/providers/react-query-provider";
import SessionProvider from "@/components/providers/session-provider";
import AuthInitializer from "@/components/providers/auth-initializer";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const accessToken = cookieStore.get("accessToken")?.value || null;
  const userCookie = cookieStore.get("user")?.value;
  const user = userCookie ? JSON.parse(userCookie) : null;
  const isAuthenticated = !!accessToken;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthInitializer 
          isAuthenticated={isAuthenticated} 
          accessToken={accessToken} 
          user={user}
        />
        <ReactQueryProvider>
          <SessionProvider>
            {children}
          </SessionProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
